apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-provider
rules:
  - apiGroups: ["github.krateo.io"]
    resources: ["repoes", "teamrepoes", "collaborators"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

  - apiGroups: ["github.krateo.io"]
    resources: ["repoes/status", "teamrepoes/status", "collaborators/status"]
    verbs: ["get", "patch", "update"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-provider
subjects:
- kind: ServiceAccount
  name: github-provider
  namespace: demo-system